### ISSUE TITLE
White space around equals sign breaks syntax highlighting

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-lucee#3]
```
component extends="root.model.text"
          persistent = "true" {
  // more code
}
```

The white space around the equals sign for `persistent` (and others, but not `extends`) breaks the syntax highlighting at `// more code`.

**Comment by jcberquist** [comment]
I am hoping the latest commits fix this issue (without breaking anything else).

**Comment by mjhagen** [comment]
I updated to latest, but it still breaks:

![](http://g.recordit.co/E7vwRVjv0M.gif)

**Comment by jcberquist** [comment]
Thanks for the GIF, I duplicated the code text you have pictured, and I cannot replicate the incorrect scoping on my machine. I tried on a mac and a windows pc, and it doesn't break when adding the space. From the GIF it looks like the regex parser is working differently on your machine than it is on mine. Are you on windows? 

In any case, I think I did some sketchy whitespace matching in the tag attribute syntax, so maybe you could try the following? Lines 363-74 in `syntaxes/cfml.sublime-syntax` should currently be:
```
    - match: '\b([a-zA-Z0-9:-]+)\s*'
      captures:
        1: entity.other.attribute-name.cfml
    - match: (=)\s*
      captures:
        1: punctuation.separator.key-value.cfml
      push:
        - include: string
        - match: '(?:[^\s<>/''"{;]|/(?!/>))+'
          scope: string.unquoted.cfml
        - match: (?<=\S)
          pop: true
```
Could you try replacing that with this and seeing if it makes a difference:
```
    - match: '\b([a-zA-Z0-9:-]+)\b'
      captures:
        1: entity.other.attribute-name.cfml
    - match: =
      scope: punctuation.separator.key-value.cfml
      push:
        - include: string
        - match: '(?<=[''"])'
          pop: true
        - match: '(?:[^\s<>/''"{;]|/(?!/>))+'
          scope: string.unquoted.cfml
          pop: true
        - match: (?=\S)
          pop: true
```
